apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  params:
  - name: prodvar
    type: string
  tasks:
    - name: test
      taskRef:
        name: test
    - name: build
      runAfter:
        - test
      taskRef:
        name: build
    - name: prod
      runAfter:
        - build
      taskRef:
        name: prod
      params:
      - name: prodvar
        value: $(params.prodvar)
