apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: prod
spec:
  params:
  - name: prodvar
    type: string
  steps:
    - name: prod
      image: ubuntu
      script: |
        #!/bin/bash
        echo "$(params.prodvar)"
